# Generated by Django 5.2.6 on 2025-09-18 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_emp_code'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salary',
            name='allowance_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Allowance %'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='basic_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_details', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='hra_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='HRA %'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='pf_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='PF %'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tax %'),
        ),
    ]
